const courses = [{
        imgSrc: './Pictures/Course-thumbnail-Algorithm.webp',
        title: 'آموزش الگوریتم و ساختمان داده به زبان ساده',
        info: 'ساختمان داده و الگوریتم، یک مهارت ضروری برای ورود به دنیای برنامه نویسیه که دیدگاه شما رو به مسائل مختلف…',
        teacher: 'رضا دولتی',
        score: 5,
        students: 497,
        price: 2300000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: true,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/elec-1-768x432.webp',
        title: 'آموزش پروژه محور Electron JS',
        info: 'ساختمان داده و الگوریتم، یک مهارت ضروری برای ورود به دنیای برنامه نویسیه که دیدگاه شما رو به مسائل مختلف…',
        teacher: 'مهرشاد براتی',
        score: 5,
        students: 4,
        price: 2200000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: true,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/nodejs.webp',
        title: 'آموزش حرفه ای NodeJS بدون پیش نیاز',
        info: 'الان و امروز کمتر کسی هست که از بازار کار داغ نود جی اس با خبر نباشه و یکی از…',
        teacher: 'محمدامین سعیدی راد',
        score: 5,
        students: 705,
        price: 3300000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/nestjs.webp',
        title: 'آموزش پروژه محور NestJS از صفر!',
        info: 'NestJS یه فریم‌ورک توسعه سمت سرور وب با TypeScript برای ساخت برنامه‌های مبتنی بر Node.js هست. نست بر پایه الگوی…',
        teacher: 'معین باغشیخی',
        score: 5,
        students: 564,
        price: 1999000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/python-data.webp',
        title: 'Data Visualization با پایتون',
        info: 'ما تو دنیایی زندگی میکنیم که همه چیز به سمت سریع تر شدن حرکت میکنه. برای ذهن انسان درک اشکال…',
        teacher: 'رضا دولتی',
        score: 5,
        students: 383,
        price: 619500,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/api-php.webp',
        title: 'آموزش جامع api نویسی با PHP',
        info: 'API یکی از پر کاربردترین اجزای نرم افزاریه که حتما باید بلد باشی! توی این دوره قراره api نویسی رو…',
        teacher: 'معین باغشیخی',
        score: 5,
        students: 101,
        price: 1200000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: true,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/gold-exp.webp',
        title: 'تجربیات طلایی من در کار تیمی',
        info: 'در ساده ترین حالت شما اگه تو یک شرکت برنامه نویسی استخدام بشین، وارد تیم اون شرکت میشین و باید…',
        teacher: 'محمدامین سعیدی راد',
        score: 5,
        students: 341,
        price: 375000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: true
    },
    {
        imgSrc: './Pictures/zero-hacker.webp',
        title: 'ورود به دنیای امنیت | هکر صفر کیلومتر',
        info: 'اگر برای ورود به دنیای امنیت سردرگم هستید. این دوره با راهنمایی مختصر و مفید و ارائه موارد تجربی باعث…',
        teacher: 'اشکان مقدس',
        score: 5,
        students: 21471,
        price: 1500000,
        offPercent: 100,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: true,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Course-thumbnail-Dashboard2-1-768x432.webp',
        title: 'پیاده سازی داشبورد های حرفه ای با CSS و JS',
        info: 'این دوره فرصتی فوق‌العاده برای ارتقاء مهارت‌های فرانت اند شماست. با یادگیری از جدیدترین تکنیک‌ها، انیمیشن‌ها ، ابزارهای پیشرفته و…',
        teacher: 'مهرشاد براتی',
        score: 5,
        students: 455,
        price: 1400000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Docker1-1-1-768x432.webp',
        title: 'آموزش Docker از صفر مطلق!',
        info: 'داکر یک پلتفرم متن باز برای طراحی؛ انتقال؛ استقرار و اجرای نرم افزار ها تحت مفهومی به نام Container می‌باشد،…',
        teacher: 'آرمین هوشمند',
        score: 5,
        students: 141,
        price: 1499000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: true,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/python-2.webp',
        title: 'بهینه نویسی کد ها در پایتون',
        info: 'همه میدونیم که زبان برنامه نویسی پایتون یه زبان خیلی جذاب، راحت و همینطور کاربردیه.  قبل از اینکه بخواین این…',
        teacher: 'رضا دولتی',
        score: 5,
        students: 821,
        price: 540000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Com_template_html_css_flexbox-1-768x432.webp',
        title: "آموزش حرفه ای طراحی قالب با Html Css FlexBox از صفر",
        info: "بعد از یادگیری Html,Css&nbsp; افراد با یک چالش بزرگی رو به رو میشن، اونم اینه که نمیتونن توسط دانشی که…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 2455,
        price: 800000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/bootstrap.webp',
        title: "آموزش بوت استرپ 5 مقدماتی تا پیشرفته (2023)",
        info: "خوش اومدین به \"آموزش بوت استرپ\" 5 سبزلرن! حتما تا الان html و css رو کامل بلدی و گذرت به…",
        teacher: "مهرشاد براتی",
        score: 5,
        students: 2405,
        price: 422000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Freelancer32-1-768x432.webp',
        title: "مستر فریلنس - هنر همکاری موفق با کارفرماها",
        info: "موفق بودن یک وکیل به تعداد بالای پرونده هاش نیست. بلکه به تعداد کیفیت پرونده هاییه که حل کرده. یک…",
        teacher: "قدیر یلمه",
        score: 5,
        students: 2044,
        price: 7100000,
        offPercent: 0,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: true
    },
    {
        imgSrc: './Pictures/Com_react-1-768x432.webp',
        title: "آموزش ری اکت ( ReactJS ) در دنیای واقعی | از 0 تا استخدام [منتورشیپ]",
        info: "حدود 99 ساعت آموزش جامع و تخصصی ری اکت!&nbsp; شما در دوره آموزش ری اکت ReactJS ، این کتابخانه قدرتمند…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 2036,
        price: 4800000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/mini-project-python.webp',
        title: "پروژه های کاربردی با پایتون",
        info: "قبل از اینکه بخواین این دوره رو ببینید اگر دوره آموزش پایتون رو ندیدین حتما دوره رو ببینید که خیلی…",
        teacher: "رضا دولتی",
        score: 5,
        students: 1734,
        price: 990000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/tailwind.webp',
        title: "آموزش جامع و پروژه محور Tailwind css",
        info: "tailwind css یک فریمورک Utility First هست، این فریمورک متشکل از یکسری کلاس های آماده ای هست که شما برای…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 1724,
        price: 899000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/nextjs.webp',
        title: 'آموزش Next.js بصورت پروژه محور',
        info: 'نکست یه فریمورک مبتنی بر ری‌اکت هست که امروزه تو بازار کار یکی از مهم‌ترین تکنولوژی‌ها برای توسعه دهنده های…',
        teacher: 'محمدامین سعیدی راد',
        score: 5,
        students: 1637,
        price: 3500000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Com_black_python-1-768x432.webp',
        title: "آموزش پایتون با گرایش امنیت | پایتون سیاه",
        info: "زبان برنامه نویسی پایتون بخاطر سادگی. قدرت. و جامعه اماری بالایی که داره تونسته جز محبوب ترین زبان های برنامه…",
        teacher: "قدیر یلمه",
        score: 5,
        students: 1596,
        price: 864000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: true,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/network-security.webp',
        title: "آموزش شبکه با گرایش امنیت | Black Network",
        info: "دنیای هک و امنیت به اندازه کافی پر چالش و جذاب هست و اگرشما بخواید وارد این حوزه بشید. حتما…",
        teacher: "اشکان مقدس",
        score: 5,
        students: 1521,
        price: 481500,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: true,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/react-libs.webp',
        title: "آموزش ۲۰ کتابخانه کاربردی ReactJS برای بازارکار",
        info: "‌کتابخانه‌ها باعث افزایش سرعت کدنویسی میشن. در حدی که تو بازار کار هم از کتابخانه های مختلفی برای توسعه پروژه‌ها…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 1504,
        price: 570000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/redux.webp',
        title: "آموزش تخصصی Redux مقدماتی تا پیشرفته",
        info: "ریداکس یه کتابخونه پراستفاده واسه مدیریت حالت های مختلف یه برنامه جاوا اسکریپتیه که تو بازار کار ری‌اکت یکی از…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 1463,
        price: 1400000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/git-github.webp',
        title: "آموزش git و github",
        info: "گیت یه Version Controller هست که نسخه های مختلف پروژه هامون رو مدیریت و نگهداری میکنن. گیت یکی از پراستفاده…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 1454,
        price: 980000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: true,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/redis.webp',
        title: "آموزش Redis برای توسعه دهندگان بک اند",
        info: "ردیس یا Redis (مخفف Remote Dictionary Server) نوعی سیستم ذخیره‌سازی متن‌باز مبتنی بر کلید-مقدار (key-Value) NoSQL است که از حافظه…",
        teacher: "معین باغشیخی",
        score: 5,
        students: 178,
        price: 990000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/tel-bot-nodejs.webp',
        title: "ساخت ربات تلگرام با NodeJS",
        info: "دوره ربات تلگرام با Nodejs یه فرصت فوق‌العاده برای یادگیری نحوه‌ی ساخت ربات‌های تلگرامی با استفاده از یکی از قدرتمندترین…",
        teacher: "معین باغشیخی",
        score: 5,
        students: 605,
        price: 1100000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/fastify.webp',
        title: "آموزش پروژه محور فریمورک Fastify",
        info: "Fastify یه فریمورک وب سریع و کم‌ حجم برای ساخت برنامه‌های تحت وب با Node.js هست.Fastify یکی از فریم‌ورک‌های جدید…",
        teacher: "معین باغشیخی",
        score: 5,
        students: 551,
        price: 700000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/api-1-768x432.webp',
        title: "درک عمیق مفاهیم API از صفر مطلق",
        info: "تو این دوره، دانشجو ها با مفاهیم پایه و اساسی API آشنا میشن و روش های مختلف استفاده از اون…",
        teacher: "معین باغشیخی",
        score: 5,
        students: 7378,
        price: 150000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/laravel-reverb.webp',
        title: "وب سوکت در لاراول با Reverb",
        info: "وب سوکت یکی از نیازهای رایجِ نرم‌افزارهای مدرن است و حالا، به لطف Reverb شما این امکان را خواهید داشت…",
        teacher: "آرمین هوشمند",
        score: 5,
        students: 5707,
        price: 120000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: true,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/webpack-1-768x432.webp',
        title: "آموزش جامع webpack",
        info: "فرقی نمی‌کند که شما یک برنامه نویس تازه کار و یا حرفه‌ای باشید؛ در هرصورت به وب‌پک نیاز خواهید داشت.…",
        teacher: "آرمین هوشمند",
        score: 5,
        students: 155,
        price: 850000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/badusb-1-768x432.webp',
        title: "تست نفوذ با BadUSB",
        info: "در این دوره کاربردی ما به مفهوم HID ATTACK و چگونگی پیاده سازی سناریو های جذاب از طریق Post Exploitation…",
        teacher: "اشکان مقدس",
        score: 5,
        students: 88,
        price: 1300000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: true,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/python.webp',
        title: "آموزش پایتون رایگان مقدماتی تا پیشرفته + پروژه های جذاب",
        info: "حیف نیست محبوب ترین زبان برنامه نویسی دنیا رو  ناقص و بی هدف یادبگیری؟ آموزش پایتون از زیر صفر و پایه…",
        teacher: "رضا دولتی",
        score: 5,
        students: 93726,
        price: 6000000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: false,
        isSecurity: false,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/js.webp',
        title: "آموزش جاوا اسکریپت رایگان مقدماتی تا پیشرفته + مینی پروژه",
        info: "آموزش جاوا اسکریپت برای تمامی افرادی ک قصد ورود به زبان برنامه نویسی دارند مناسب می باشد . خصوصا برای…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 71003,
        price: 4000000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/html.webp',
        title: "آموزش HTML رایگان مقدماتی تا پیشرفته",
        info: "آموزش HTML، اولین قدم شروع طراحی وبسایت است. HTML یه زبان نشانه گذاری هست که با کمک اون میتونی تگ…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 61886,
        price: 220000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/css.webp',
        title: "آموزش Css رایگان مقدماتی تا پیشرفته",
        info: "حالا وقتشه که با دوره آموزش CSS به اسکلتی که با html ساختی پوست و گوشت بدی تا تبدیل به…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 54027,
        price: 150000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/html-css.webp',
        title: "پروژه های خلاقانه با Html و Css(آپدیت  ۲۰۲۳)",
        info: "دوره  پروژه خلاقانه با HTML, CSS  با هدف تقویت CSS شما, با آموزش پروژه‌های پیشرفته و سطح بالا , طراحی…",
        teacher: "مهرشاد براتی",
        score: 5,
        students: 35839,
        price: 220000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/css-grid.webp',
        title: "آموزش پروژه محور CSS Grid + پروژه لندینگ رستوران",
        info: "Css grid یک ماژول مربوط به css است . کارکردن با این ماژول بسیار جذاب است و با امکانات و…",
        teacher: "مهرشاد براتی",
        score: 5,
        students: 32365,
        price: 35000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/flexbox.webp',
        title: "آموزش FlexBox پروژه محور + پروژه سایت هاستینگ",
        info: "اگر شما به حوزه طراحی و برنامه نویسی وب علاقه داشته باشید قطعا در مورد صفحه آرایی، ریسپانسیو سازی، فلکس…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 31895,
        price: 196000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/black-js.webp',
        title: "آموزش جاوااسکریپت با گرایش امنیت | جاوااسکریپت سیاه",
        info: "جاوااسکریپت همواره در لیست محبوب ترین زبان های برنامه نویسی برای هکرها و امنیت کارهاست ! و من در این دوره…",
        teacher: "قدیر یلمه",
        score: 5,
        students: 31114,
        price: 150000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: false,
        isSecurity: true,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    }
]

const blogs = [{
        imgSrc: "./Pictures/how-long-takes-learn-html.jpg",
        title: "یادگیری html چقدر طول میکشد؟",
        info: "آیا تا به حال به این فکر کرده‌اید که چطور وب‌سایت‌ها ساخته می‌شوند؟ شاید شنیده‌اید که برای ساختن یک وب‌سایت، باید HTML را یاد بگیرید. اما شاید این سؤال برایتان…",
        author: "مهدی ایلخانی نسب",
        dateDay: 19,
        dateMonth: 6,
        dateYear: 1403,
        isHtml: true,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: "./Pictures/Animated-text-html-code.webp",
        title: "کد html متن متحرک",
        info: "در دنیای وب امروز، استفاده از کدهای HTML متن متحرک در صفحات وب جزو مهمترین ترفندها برای جلب توجه کاربران در بنرها و متون تبلیغاتی و همینطور زیباسازی محتوا محسوب…",
        author: "زهرا سپنج پور",
        dateDay: 23,
        dateMonth: 10,
        dateYear: 1402,
        isHtml: true,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: "./Pictures/What-is-doctype.webp",
        title: "Doctype چیست؟ اهمیت DOCTYPE در html",
        info: "جواب سوال DOCTYPE چیست؟ در عین اهمیت، کاملا ساده ست! با یه سوال شروع کنیم. فکر می کنید دلیل اینکه با هر مرورگری یک صفحه وب رو باز می کنید،…",
        author: "زهرا سپنج پور",
        dateDay: 18,
        dateMonth: 9,
        dateYear: 1402,
        isHtml: true,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/the-difference-between-bootstrap-4-and-5-768x461.webp",
        title: "تفاوت بوت استرپ 4 و 5 چیست ؟",
        info: "برنامه نویسی در حوزه طراحی وب همواره دارای چالش‌های متعددی است که توسعه دهندگان همواره با آنها سروکار دارند. یکی از مشکلاتی که هر از مدتی برای این افراد پیش…",
        author: "محمد رحمانیان",
        dateDay: 25,
        dateMonth: 12,
        dateYear: 1402,
        isHtml: false,
        isBootstrap: true,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/Bootstrap-installation-tutorial-4-768x432.png",
        title: "آموزش نصب بوت استرپ- راهنمای نصب تمامی ورژن های bootstrap",
        info: "سلام دوستان عزیز و همراهان همیشگی سبزلرن. در این مقاله قصد داریم آموزش نصب بوت استرپ را به شما ارائه بدیم. همون طور که میدونین بوت استرپ محبوب ترین و پراستفاده…",
        author: "محمدامین سعیدی راد",
        dateDay: 20,
        dateMonth: 7,
        dateYear: 1399,
        isHtml: false,
        isBootstrap: true,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/Bootstrap-Grading-Tutorial-4-768x432.png",
        title: "آموزش گرید بندی در بوت استرپ 4 + ویدئو",
        info: "سلام دوستان عزیز و همراهان همیشگی سبزلرن، مستقیم میرم سر اصل مطلب، همونطور که میدونین بوت استرپ یک فریمورک برای ریسپانسیو کردن صفحات وب هست، تو این مقاله میخوایم در…",
        author: "محمدامین سعیدی راد",
        dateDay: 25,
        dateMonth: 7,
        dateYear: 1399,
        isHtml: false,
        isBootstrap: true,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/what-is-ddos-attack.webp",
        title: "حمله ddos چیست",
        info: "مسئله امنیت امروزه یک بحث بسیار حساس است که اکثر شرکت‌ها و کسب وکارها نگران آن هستند؛ و منظورم از امنیت، امنیت سایبری است. از جمله حملات سایبری میتوانم به…",
        author: "ارمیا مزرعه",
        dateDay: 11,
        dateMonth: 6,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: true,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/prog-languages-for-hack.jpg",
        title: "زبان های برنامه نویسی برای هک و امنیت",
        info: "دنیای دیجیتال امروز پر از فرصت‌ها و چالش‌های مختلف است. یکی از بزرگ‌ترین چالش‌ها، حفظ امنیت در برابر حملات سایبری و هکرهاست. هر روزه خبرهای جدیدی از نقض اطلاعات، حملات…",
        author: "مهدی ایلخانی نسب",
        dateDay: 10,
        dateMonth: 6,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: true,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/10-python-libs-for-hack.webp",
        title: "10 کتابخانه پایتون برای هک و امنیت",
        info: "در این مقاله به 10 تا از بهترین کتابخانه پایتون برای هک و امنیت می پردازیم. همونطور که میدونید زبان پایتون توی هک و امنیت شاه بقیه زبان ها حساب میشه!…",
        author: "حسین مستقیمی",
        dateDay: 14,
        dateMonth: 6,
        dateYear: 1401,
        isHtml: false,
        isBootstrap: false,
        isSecurity: true,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/what-is-jquery-1-768x461.webp",
        title: "JQuery چیست ؟",
        info: "کتابخانه‌ها در برنامه نویسی، مجموعه‌ای از توابع، ماژول‌ها و کدهای از قبل نوشته شده هستند که باعث افزایش سرعت توسعه و کاهش خطاهای ناخواسته می‌شوند. زبان برنامه نویسی جاوا اسکریپت…",
        author: "محمد رحمانیان",
        dateDay: 25,
        dateMonth: 12,
        dateYear: 1402,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: true,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/The-difference-between-JavaScript-and-jQuery-2020-768x432.png",
        title: "تفاوت جاوا اسکریپت با جی کوئری – برنده کیست، جاوا اسکریپت یا جی کوئری + ویدئو (2020)",
        info: "سلام خدمت شما کاربران محترم وب سایت سبز لرن، در این مقاله می خواهیم در مورد تفاوت جاوا اسکریپت با جی کوئری صحبت کنیم. جی کوئری یا jquery و جاوا…",
        author: "زهرا شوشتری",
        dateDay: 28,
        dateMonth: 7,
        dateYear: 1399,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: true,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/Events-in-jQuery-768x432.png",
        title: "رویداد ها در جی کوئری- اتفاقات پرماجرای سایت شما + ویدئو",
        info: "سلام به همه ی دوستای عزیز سایت سبزلرن امیدوارم حال دلتون خوب باشه تو این مقاله میخوام در رابطه با رویداد ها در جی کوئری صحبت کنم. رویدادهای جی کوئری…",
        author: "زهرا شوشتری",
        dateDay: 13,
        dateMonth: 7,
        dateYear: 1399,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: true,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/what-is-react.png",
        title: "ری اکت چیست و چه کاربرد هایی دارد؟ + 5 دلیل استفاده از ری اکت",
        info: "ری اکت چیست؟ تصور کنید یک مهندس طراحی خودرو نخبه، قصد داره یک ماشین جدید و جذاب بسازه. این مهندس ما دو راه برای رسیدن به هدفش داره! ما در…",
        author: "محمدامین سعیدی راد",
        dateDay: 26,
        dateMonth: 3,
        dateYear: 1400,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: true,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/کامپوننت-ها-در-ری-اکت-768x432.png",
        title: "کامپوننت ها در ری اکت – قابلیت فوق العاده این کتابخانه + ویدئو",
        info: "سلام به همه ی دوستان عزیز سایت سبزلرن امیدوارم حال دلتون خوب باشه . مقاله ی امروز ما راجب کامپوننت ها در ری اکت هست و قراره که باهم اون…",
        author: "زهرا شوشتری",
        dateDay: 10,
        dateMonth: 7,
        dateYear: 1399,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: true,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/learn-inistallation-react-768x432.png",
        title: "آموزش نصب ری اکت جی اس به چند روش ساده ولی حرفه‌ای + ویدئو",
        info: "در این مقاله آموزش نصب ری کت جی اس  رو براتون اماده کردیم تا بتونین براحتی ازش استفاده کنین. همون طور که میدونید ری اکت جی اس یا همون react…",
        author: "زهرا شوشتری",
        dateDay: 8,
        dateMonth: 7,
        dateYear: 1399,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: true,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/css-768x432.webp",
        title: "css چیست و چه کاربردی دارد؟",
        info: "در دنیای وب، به نظر می‌رسد همه چیز بر اساس زیبایی و قدرت گرافیکی استوار است. اما آیا همه آن زیبایی و جذابیت که در هر وب‌سایت دیده می‌شود، صرفاً…",
        author: "شقایق ستیه نیا",
        dateDay: 7,
        dateMonth: 2,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: true,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/what-is-flexbox-1-768x512.webp",
        title: "flexbox چیست؟",
        info: "flexbox چیست؟ و اساساً چه نقشی در توسعه وب دارد و آیا باید هر طراح سایتی با این مفهوم آشنا باشد؟ به زبان بسیار ساده، Flexbox نوعی مدل چیدمان قدرتمند…",
        author: "کامل بهرامی",
        dateDay: 9,
        dateMonth: 12,
        dateYear: 1402,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: true,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/grid-in-scc-shaxes-100-768x432.jpg",
        title: "grid در css چیست",
        info: "اگر با سیستم لی‌اوت صفحات وب آشنایی ندارید؛ پس حتما نمی‌دانید grid در css چیست و چه ‌کاربردی دارد. منظور از لی‌اوت شبکه‌بندی صفحه‌ی وب است که کار چیدمان عناصر…",
        author: "زهرا آقاخانی",
        dateDay: 4,
        dateMonth: 12,
        dateYear: 1400,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: true,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/رابط-کاربری-یا-User-Interface-چیست؟-768x427.webp",
        title: "رابط کاربری یا User Interface چیست و چه کاربردی دارد؟",
        info: "رابط کاربری یا UI ممکن است شامل دکمه‌ها، منوها، تایپوگرافی و عناصر مختلفی باشد و اولین چیزی است که کاربر در سایت مشاهده کرده و با آن تعامل می‌کند. یک…",
        author: "محمد رحمانیان",
        dateDay: 20,
        dateMonth: 3,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: true,
        isVue: false
    }, {
        imgSrc: "./Pictures/how-to-become-ui-ux-designer.jpg",
        title: "چگونه ui و ux کار شویم؟",
        info: "اگر شماهم این روزها زیاد افرادی رو می‌بینید که با ui و ux پروژه‌های خفنی را پیاده سازی می‌کنند احتمالا مدام می‌پرسید: چگونه ui و ux کار شویم؟ که این…",
        author: "ارمیا مزرعه",
        dateDay: 11,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: true,
        isVue: false
    }, {
        imgSrc: "./Pictures/front-end-back-end-differences.webp",
        title: "فرق بک اند و فرانت اند چیست",
        info: "بک اند و فرانت اند پایه و اساس تمام سایت‌هایی است که امروزه مشاهده می‌کنید؛ یک سایت بدون این 2 بخش وجود نخواهد داشت و شما نمیتوانید سایت را فقط…",
        author: "ارمیا مزرعه",
        dateDay: 31,
        dateMonth: 5,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: true,
        isVue: false
    }, {
        imgSrc: "./Pictures/what-is-vue.webp",
        title: "Vue JS چیست ؟",
        info: "یکی از بخش‌های مهم در توسعه یک پروژه، نحوه تعامل کاربران با پروژه است؛ جایی که اهمیت طراحی رابط کاربری یا UI Design بیشتر به چشم می‌آید. در توسعه وب،…",
        author: "محمد رحمانیان",
        dateDay: 7,
        dateMonth: 2,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: true
    }, {
        imgSrc: "./Pictures/applications-of-vue-js-768x432.png",
        title: "کاربرد های ویو جی اس – پلتفرم پرآوازه‌ و دوست داشتنی جاوا اسکریپت + ویدئو",
        info: "سلام دوستان عزیز و همراهان همیشگی سایت سبزلرن تو این مقاله قصد دارم در مورد کاربرد های ویو جی اس این فریمورک قدرتمند صحبت کنیم. همون طور که میدونین ویو…",
        author: "محمدامین سعیدی راد",
        dateDay: 12,
        dateMonth: 8,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: true
    }, {
        imgSrc: "./Pictures/Vue-Js-installation-tutorial-768x432.png",
        title: "آموزش نصب ویو جی اس (Vue Js) + ویدئو",
        info: "ویو جی اس رو میشه به چندین روش نصب و استفاده کرد که ممکن است برخی از دوستان در زمینه نصب و استفاده از آن مشکل داشته باشند، تو این…",
        author: "محمدامین سعیدی راد",
        dateDay: 3,
        dateMonth: 8,
        dateYear: 1399,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: true
    }, {
        imgSrc: './Pictures/flowchart.jpg',
        title: "فلوچارت برنامه نویسی چیست؟",
        info: "در این مقاله از سبزلرن، به معرفی و اهمیت فلوچارت برنامه ‌نویسی پرداخته و روش‌ها و فواید آن را برای برنامه‌نویسان مورد بررسی قرار خواهیم داد. همچنین، به روش‌های استفاده…",
        author: "ارمیا مزرعه",
        dateDay: 19,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/why-cant-learn-prog.webp',
        title: "چرا برنامه نویسی یاد نمی گیرم؟ 5 مانع یادگیری برنامه نویسی",
        info: "آیا تا به حال برای یادگیری برنامه‌نویسی تلاش کرده‌اید ولی به نظر رسیده که هیچ‌وقت به جایی نمی‌رسید؟ انگار هر چقدر هم تلاش می‌کنید، باز هم کدها مثل یک زبان…",
        author: "مهدی ایلخانی نسب",
        dateDay: 18,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/cod.webp',
        title: "زبان برنامه نویسی بازی کال اف دیوتی موبایل",
        info: "بازی «کال آو دیوتی موبایل» یکی از آن بازی‌هایی است که خیلی‌ها را پای موبایلشان میخکوب کرده است. گرافیک فوق‌العاده، گیم‌پلی هیجان‌انگیز و تجربه‌ای که حس یک بازی کنسولی واقعی…",
        author: "مهدی ایلخانی نسب",
        dateDay: 17,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/full-stack-roadmap-blog.webp',
        title: "نقشه راه برنامه نویس فول استک وب",
        info: "اگر به برنامه‌نویسی علاقه دارید و یا حتی چند وقتی است که مشغول یادگیری هستید، احتمالاً اصطلاح “برنامه‌نویس فول استک” به گوشتان خورده است. اما چه چیزی باعث شده که…",
        author: "مهدی ایلخانی نسب",
        dateDay: 16,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/best-way-to-learn-prog.webp',
        title: "بهترین روش یادگیری برنامه نویسی، خودآموز یا کلاس حضوری؟",
        info: "این روزها، برنامه‌نویسی دیگه یک مهارت اختیاری نیست، بلکه یکی از کلیدهای اصلی موفقیت در دنیای مدرنه. از ساختن اپلیکیشن‌های کاربردی تا تبدیل کردن ایده‌های ذهنی به واقعیت، برنامه‌نویسی راه‌های…",
        author: "مهدی ایلخانی نسب",
        dateDay: 21,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/what-is-machine-learning.jpg',
        title: "ماشین لرنینگ چیست؟",
        info: "دانشگاه‌ها و شرکت‌ها به دنبال روش‌های پیشرفته‌ای برای پردازش داده‌ها و انجام پیش‌بینی‌های دقیق تر هستند. یکی از روش‌های محبوب در این زمینه، ماشین لرنینگ است. در این مقاله از…",
        author: "ارمیا مزرعه",
        dateDay: 21,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/complete-guide-to-progs-where-to-start.webp',
        title: "راهنمای کامل مهاجرت کاری برای برنامه‌نویسان: از کجا شروع کنیم؟",
        info: "دنیای برنامه‌نویسی هر روز در حال گسترش است، و با آن، فرصت‌های مهاجرت کاری نیز گسترده‌تر می‌شود. شاید بارها فکر کرده باشید که اگر بتوانید مهارت‌های خود را در جایی…",
        author: "مهدی ایلخانی نسب",
        dateDay: 20,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/what-is-data-science.webp',
        title: "دیتا ساینس چیست؟ آشنایی با مفاهیم اصلی علم داده و کاربردهای آن",
        info: "در دنیایی که داده‌ها به‌سرعت در حال تولید و تغییر هستند، قدرت در دست کسانی است که بتوانند داده‌ها را درک، تحلیل و به تصمیمات هوشمندانه تبدیل کنند. دیتا ساینس…",
        author: "مهدی ایلخانی نسب",
        dateDay: 25,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/seven-tips-progs-parenst-should-know.webp',
        title: "7 نکته که والدین باید قبل از شروع برنامه‌نویسی برای کودکان بدانند",
        info: "امروزه وقتی حرف از مهارت‌های مهم قرن ۲۱ می‌زنیم، برنامه‌نویسی دقیقاً مثل یک ستاره درخشان توی این لیست دیده می‌شه. مثل وقتی که یادگیری زبان انگلیسی یا ریاضیات برامون ضروریه،…",
        author: "مهدی ایلخانی نسب",
        dateDay: 24,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/what-is-it.webp',
        title: "IT چیست؟ آشنایی با فناوری اطلاعات و کاربردهای آن",
        info: "IT چیست؟ در دنیای مدرن امروز IT یکی از ارکان اصلی هر سازمان و کسب‌وکاری است که می‌خواهد از دنیای دیجیتال عقب نماند! در واقع اگر بخواهیم یک تعریف ساده…",
        author: "مهدی ایلخانی نسب",
        dateDay: 23,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/google-colab.jpg',
        title: "گوگل کولب چیست؟",
        info: "گوگل کولب یکی از خدمات قدرتمند و محبوب شرکت گوگل است که به شرکت‌ها و افراد این امکان را می‌دهد تا در محیطی ابری، منابع محاسباتی و ذخیره‌سازی داده را…",
        author: "ارمیا مزرعه",
        dateDay: 28,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/best-prog-language-for-usa.webp',
        title: "بهترین زبان برنامه نویسی برای مهاجرت به آمریکا",
        info: "وقتی صحبت از مهاجرت به آمریکا می‌شود، شاید اولین چیزهایی که به ذهنتان برسد، قوانین مهاجرت، ویزا و البته مصاحبه‌های سخت باشد. اما اگر برنامه‌نویس هستید یا قصد دارید برنامه‌نویسی…",
        author: "مهدی ایلخانی نسب",
        dateDay: 27,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    },
    {
        imgSrc: './Pictures/chatgpt-canvas.webp',
        title: "ChatGPT Canvas: تازه‌واردی که دنیای برنامه‌نویسی را تغییر می‌دهد؟",
        info: "دنیای برنامه‌نویسی به سرعت در حال تغییر است. هر روز ابزارهای جدیدی معرفی می‌شوند که زندگی ما برنامه‌نویسان را راحت‌تر می‌کنند. اما وقتی صحبت از هوش مصنوعی می‌شود، چیزهایی که…",
        author: "مهدی ایلخانی نسب",
        dateDay: 25,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }, {
        imgSrc: "./Pictures/42.-5-اشتباه-رایج-کدنویسی-که-مبتدی-ها-باید-بدانند-768x384.webp",
        title: "5 اشتباه رایج کدنویسی که مبتدی ها باید بدانند!",
        info: "کدنویسی یک دنیای هیجان‌انگیز است. شروع این سفر پر از چالش‌های جدید می‌تواند فوق‌العاده باشد، اما طبیعی است که در مسیر یادگیری با اشتباهاتی روبرو شوید. خبر خوب این است…",
        author: "مهدی ایلخانی نسب",
        dateDay: 29,
        dateMonth: 7,
        dateYear: 1403,
        isHtml: false,
        isBootstrap: false,
        isSecurity: false,
        isJquery: false,
        isReact: false,
        isCss: false,
        isWebDesign: false,
        isVue: false
    }
]

const teachers = [{
        imgSrc: "./Pictures/amin-saeedi-rad-profile.png",
        name: 'محمدامین سعیدی راد',
        bio: 'اولین کدم رو 14 سالگی زدم، حدود 9 سال پیش که با زبان ویژوال بیسیک بود و بعد حدودا 2 سال تو فیلد برنامه نویسی موبایل با زبان جاوا کار کردم و در نهایت با عشقی به اسم جاوا اسکریپت آشنا شدم و حدودا یه 7 سالی هست جاوا اسکریپت کد می‌زنم و به صورت Mern Stack فعالیت می‌کنم.',
        socials: {
            github: '',
            linkedin: '',
            telegram: 'https://t.me/aminkhoy78',
            instagram: 'https://www.instagram.com/rad_front'
        },
        skills: ['Html', 'Css', 'JavaScript', 'React.js', 'Redux', 'Next.js', 'Node.js']
    },
    {
        imgSrc: "./Pictures/ashkan-moghadas.png",
        name: 'اشکان مقدس',
        bio: 'تقریبا 8 سالی هست که تو حوزه هک و امنیت فعالیت میکنم علاقه اصلیم بحث تهاجمی (Offensive) هست ، 3 سالی هست که توی حوزه تیم قرمز (RedTeam) فعالیت میکنم و به نظرم همه حوزه های هک جذابه و نمیشه از دستش داد :)',
        socials: {
            github: 'github.com/ultrasecurity',
            linkedin: '',
            telegram: '',
            instagram: ''
        },
        skills: []
    },
    {
        imgSrc: "./Pictures/qadir-yolme.png",
        name: 'قدیر یلمه',
        bio: '',
        socials: {
            github: 'https://github.com/joshkar',
            linkedin: '',
            telegram: '',
            instagram: 'https://instagram.com/qadiryolme'
        },
        skills: []
    },
    {
        imgSrc: "./Pictures/mehrshad-barati.png",
        name: 'مهرشاد براتی',
        bio: 'مهرشاد براتی هستم برنامه نویس و توسعه دهنده فول استک وب و دانشجوی ارشد رشته کامپیوتر گرایش نرم افزار',
        socials: {
            github: '',
            linkedin: '',
            telegram: 'https://t.me/source_code_1',
            instagram: 'https://instagram.com/mehrshad.barati2020?igshid=MzRlODBiNWFlZA=='
        },
        skills: []
    },
    {
        imgSrc: "./Pictures/reza-dolati.png",
        name: 'رضا دولتی',
        bio: 'تقریبا 10 ساله در زمینه برنامه نویسی فعال هستم، 5 سال پیش اولین شرکت خودم رو تاسیس کردم، 1 سال پیش اولین فروشگاه اینترنتی خودم رو توسعه دادم. عاشق زبان برنامه نویسی پایتون هستم و در کنار پایتون زبان های دیگه ای رو هم کار میکنم. در حال حاضر، توسعه دهنده بک اند با جنگو و فارغ التحصیل رشته امنیت از دانشگاه سراسری تبریز هستم و 3 ساله در زمینه هوش مصنوعی هم فعالیت میکنم.',
        socials: {
            github: 'https://github.com/rezadolati01',
            linkedin: '',
            telegram: 'https://t.me/rezadolati01',
            instagram: 'https://instagram.com/rezadolati01?igshid=MzRlODBiNWFlZA=='
        },
        skills: []
    },
    {
        imgSrc: "./Pictures/armin-hooshmand.png",
        name: 'آرمین هوشمند',
        bio: 'برنامه نویس ارشد وب',
        socials: {
            github: 'https://github.com/RealMrHex',
            linkedin: '',
            telegram: 'https://t.me/MentionHex',
            instagram: ''
        },
        skills: []
    },
    {
        imgSrc: "./Pictures/hamidreza-ebadi.png",
        name: 'حمیدرضا عبادی',
        bio: 'توسعه دهنده فرانت اند سبزلرن <br> فعال در زمینه طراحی و توسعه وبسایت و طراحی محصول',
        socials: {
            github: '',
            linkedin: 'http://www.linkedin.com/in/hamidreza-ebadi-3a6940223',
            telegram: 'https://t.me/ebadidev',
            instagram: 'https://instagram.com/ebadi.dev'
        },
        skills: ['Web Development']
    },
    {
        imgSrc: "./Pictures/moein-baghsheikhi.png",
        name: 'معین باغشیخی',
        bio: '6 سال هست که برنامه نویسی رو شروع کردم؛ با فرانت استارت زدم و و حدود دو سال در زمینه برنامه نویسی فرانت و وردپرس فعالیت میکردم. بعد از اون رفتم سمت بکند و چهار سالی میشه که با PHP و NodeJS کد میزنم',
        socials: {
            github: 'https://github.com/moeinbaghsheikhi',
            linkedin: '',
            telegram: 'https://t.me/moeinbaghsheikhi',
            instagram: 'https://www.instagram.com/moein_code/'
        },
        skills: ['HTML', 'CSS', 'Bootstrap', 'Tailwind', 'javascript', 'php', 'laravel', 'nodeJS', 'expressJS', 'NestJS', 'MySQL', 'Postgresql', 'MongoDB']
    }
]

export {
    courses,
    blogs,
    teachers
}