const courses = [{
        imgSrc: './Pictures/Course-thumbnail-Algorithm.webp',
        title: 'آموزش الگوریتم و ساختمان داده به زبان ساده',
        info: 'ساختمان داده و الگوریتم، یک مهارت ضروری برای ورود به دنیای برنامه نویسیه که دیدگاه شما رو به مسائل مختلف…',
        teacher: 'رضا دولتی',
        score: 5,
        students: 497,
        price: 2300000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: true,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/elec-1-768x432.webp',
        title: 'آموزش پروژه محور Electron JS',
        info: 'ساختمان داده و الگوریتم، یک مهارت ضروری برای ورود به دنیای برنامه نویسیه که دیدگاه شما رو به مسائل مختلف…',
        teacher: 'مهرشاد براتی',
        score: 5,
        students: 4,
        price: 2200000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: true,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/nodejs.webp',
        title: 'آموزش حرفه ای NodeJS بدون پیش نیاز',
        info: 'الان و امروز کمتر کسی هست که از بازار کار داغ نود جی اس با خبر نباشه و یکی از…',
        teacher: 'محمدامین سعیدی راد',
        score: 5,
        students: 705,
        price: 3300000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/nestjs.webp',
        title: 'آموزش پروژه محور NestJS از صفر!',
        info: 'NestJS یه فریم‌ورک توسعه سمت سرور وب با TypeScript برای ساخت برنامه‌های مبتنی بر Node.js هست. نست بر پایه الگوی…',
        teacher: 'معین باغشیخی',
        score: 5,
        students: 564,
        price: 1999000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/python-data.webp',
        title: 'Data Visualization با پایتون',
        info: 'ما تو دنیایی زندگی میکنیم که همه چیز به سمت سریع تر شدن حرکت میکنه. برای ذهن انسان درک اشکال…',
        teacher: 'رضا دولتی',
        score: 5,
        students: 383,
        price: 619500,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/api-php.webp',
        title: 'آموزش جامع api نویسی با PHP',
        info: 'API یکی از پر کاربردترین اجزای نرم افزاریه که حتما باید بلد باشی! توی این دوره قراره api نویسی رو…',
        teacher: 'معین باغشیخی',
        score: 5,
        students: 101,
        price: 1200000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: true,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/gold-exp.webp',
        title: 'تجربیات طلایی من در کار تیمی',
        info: 'در ساده ترین حالت شما اگه تو یک شرکت برنامه نویسی استخدام بشین، وارد تیم اون شرکت میشین و باید…',
        teacher: 'محمدامین سعیدی راد',
        score: 5,
        students: 341,
        price: 375000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: true
    },
    {
        imgSrc: './Pictures/zero-hacker.webp',
        title: 'ورود به دنیای امنیت | هکر صفر کیلومتر',
        info: 'اگر برای ورود به دنیای امنیت سردرگم هستید. این دوره با راهنمایی مختصر و مفید و ارائه موارد تجربی باعث…',
        teacher: 'اشکان مقدس',
        score: 5,
        students: 21471,
        price: 1500000,
        offPercent: 100,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: true,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Course-thumbnail-Dashboard2-1-768x432.webp',
        title: 'پیاده سازی داشبورد های حرفه ای با CSS و JS',
        info: 'این دوره فرصتی فوق‌العاده برای ارتقاء مهارت‌های فرانت اند شماست. با یادگیری از جدیدترین تکنیک‌ها، انیمیشن‌ها ، ابزارهای پیشرفته و…',
        teacher: 'مهرشاد براتی',
        score: 5,
        students: 455,
        price: 1400000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Docker1-1-1-768x432.webp',
        title: 'آموزش Docker از صفر مطلق!',
        info: 'داکر یک پلتفرم متن باز برای طراحی؛ انتقال؛ استقرار و اجرای نرم افزار ها تحت مفهومی به نام Container می‌باشد،…',
        teacher: 'آرمین هوشمند',
        score: 5,
        students: 141,
        price: 1499000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: true,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/python-2.webp',
        title: 'بهینه نویسی کد ها در پایتون',
        info: 'همه میدونیم که زبان برنامه نویسی پایتون یه زبان خیلی جذاب، راحت و همینطور کاربردیه.  قبل از اینکه بخواین این…',
        teacher: 'رضا دولتی',
        score: 5,
        students: 821,
        price: 540000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Com_template_html_css_flexbox-1-768x432.webp',
        title: "آموزش حرفه ای طراحی قالب با Html Css FlexBox از صفر",
        info: "بعد از یادگیری Html,Css&nbsp; افراد با یک چالش بزرگی رو به رو میشن، اونم اینه که نمیتونن توسط دانشی که…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 2455,
        price: 800000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/bootstrap.webp',
        title: "آموزش بوت استرپ 5 مقدماتی تا پیشرفته (2023)",
        info: "خوش اومدین به \"آموزش بوت استرپ\" 5 سبزلرن! حتما تا الان html و css رو کامل بلدی و گذرت به…",
        teacher: "مهرشاد براتی",
        score: 5,
        students: 2405,
        price: 422000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Freelancer32-1-768x432.webp',
        title: "مستر فریلنس - هنر همکاری موفق با کارفرماها",
        info: "موفق بودن یک وکیل به تعداد بالای پرونده هاش نیست. بلکه به تعداد کیفیت پرونده هاییه که حل کرده. یک…",
        teacher: "قدیر یلمه",
        score: 5,
        students: 2044,
        price: 7100000,
        offPercent: 0,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: true
    },
    {
        imgSrc: './Pictures/Com_react-1-768x432.webp',
        title: "آموزش ری اکت ( ReactJS ) در دنیای واقعی | از 0 تا استخدام [منتورشیپ]",
        info: "حدود 99 ساعت آموزش جامع و تخصصی ری اکت!&nbsp; شما در دوره آموزش ری اکت ReactJS ، این کتابخانه قدرتمند…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 2036,
        price: 4800000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/mini-project-python.webp',
        title: "پروژه های کاربردی با پایتون",
        info: "قبل از اینکه بخواین این دوره رو ببینید اگر دوره آموزش پایتون رو ندیدین حتما دوره رو ببینید که خیلی…",
        teacher: "رضا دولتی",
        score: 5,
        students: 1734,
        price: 990000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/tailwind.webp',
        title: "آموزش جامع و پروژه محور Tailwind css",
        info: "tailwind css یک فریمورک Utility First هست، این فریمورک متشکل از یکسری کلاس های آماده ای هست که شما برای…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 1724,
        price: 899000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/nextjs.webp',
        title: 'آموزش Next.js بصورت پروژه محور',
        info: 'نکست یه فریمورک مبتنی بر ری‌اکت هست که امروزه تو بازار کار یکی از مهم‌ترین تکنولوژی‌ها برای توسعه دهنده های…',
        teacher: 'محمدامین سعیدی راد',
        score: 5,
        students: 1637,
        price: 3500000,
        offPercent: 30,
        isLastCourses: true,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/Com_black_python-1-768x432.webp',
        title: "آموزش پایتون با گرایش امنیت | پایتون سیاه",
        info: "زبان برنامه نویسی پایتون بخاطر سادگی. قدرت. و جامعه اماری بالایی که داره تونسته جز محبوب ترین زبان های برنامه…",
        teacher: "قدیر یلمه",
        score: 5,
        students: 1596,
        price: 864000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: true,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/network-security.webp',
        title: "آموزش شبکه با گرایش امنیت | Black Network",
        info: "دنیای هک و امنیت به اندازه کافی پر چالش و جذاب هست و اگرشما بخواید وارد این حوزه بشید. حتما…",
        teacher: "اشکان مقدس",
        score: 5,
        students: 1521,
        price: 481500,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: true,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/react-libs.webp',
        title: "آموزش ۲۰ کتابخانه کاربردی ReactJS برای بازارکار",
        info: "‌کتابخانه‌ها باعث افزایش سرعت کدنویسی میشن. در حدی که تو بازار کار هم از کتابخانه های مختلفی برای توسعه پروژه‌ها…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 1504,
        price: 570000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/redux.webp',
        title: "آموزش تخصصی Redux مقدماتی تا پیشرفته",
        info: "ریداکس یه کتابخونه پراستفاده واسه مدیریت حالت های مختلف یه برنامه جاوا اسکریپتیه که تو بازار کار ری‌اکت یکی از…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 1463,
        price: 1400000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/git-github.webp',
        title: "آموزش git و github",
        info: "گیت یه Version Controller هست که نسخه های مختلف پروژه هامون رو مدیریت و نگهداری میکنن. گیت یکی از پراستفاده…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 1454,
        price: 980000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: true,
        isLatestCourses: false,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: true,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/redis.webp',
        title: "آموزش Redis برای توسعه دهندگان بک اند",
        info: "ردیس یا Redis (مخفف Remote Dictionary Server) نوعی سیستم ذخیره‌سازی متن‌باز مبتنی بر کلید-مقدار (key-Value) NoSQL است که از حافظه…",
        teacher: "معین باغشیخی",
        score: 5,
        students: 178,
        price: 990000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/tel-bot-nodejs.webp',
        title: "ساخت ربات تلگرام با NodeJS",
        info: "دوره ربات تلگرام با Nodejs یه فرصت فوق‌العاده برای یادگیری نحوه‌ی ساخت ربات‌های تلگرامی با استفاده از یکی از قدرتمندترین…",
        teacher: "معین باغشیخی",
        score: 5,
        students: 605,
        price: 1100000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/fastify.webp',
        title: "آموزش پروژه محور فریمورک Fastify",
        info: "Fastify یه فریمورک وب سریع و کم‌ حجم برای ساخت برنامه‌های تحت وب با Node.js هست.Fastify یکی از فریم‌ورک‌های جدید…",
        teacher: "معین باغشیخی",
        score: 5,
        students: 551,
        price: 700000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/api-1-768x432.webp',
        title: "درک عمیق مفاهیم API از صفر مطلق",
        info: "تو این دوره، دانشجو ها با مفاهیم پایه و اساسی API آشنا میشن و روش های مختلف استفاده از اون…",
        teacher: "معین باغشیخی",
        score: 5,
        students: 7378,
        price: 150000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/laravel-reverb.webp',
        title: "وب سوکت در لاراول با Reverb",
        info: "وب سوکت یکی از نیازهای رایجِ نرم‌افزارهای مدرن است و حالا، به لطف Reverb شما این امکان را خواهید داشت…",
        teacher: "آرمین هوشمند",
        score: 5,
        students: 5707,
        price: 120000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: false,
        isPython: false,
        isPHP: true,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/webpack-1-768x432.webp',
        title: "آموزش جامع webpack",
        info: "فرقی نمی‌کند که شما یک برنامه نویس تازه کار و یا حرفه‌ای باشید؛ در هرصورت به وب‌پک نیاز خواهید داشت.…",
        teacher: "آرمین هوشمند",
        score: 5,
        students: 155,
        price: 850000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/badusb-1-768x432.webp',
        title: "تست نفوذ با BadUSB",
        info: "در این دوره کاربردی ما به مفهوم HID ATTACK و چگونگی پیاده سازی سناریو های جذاب از طریق Post Exploitation…",
        teacher: "اشکان مقدس",
        score: 5,
        students: 88,
        price: 1300000,
        offPercent: 30,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: true,
        isMostPopularCourses: false,
        isFrontEnd: false,
        isSecurity: true,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/python.webp',
        title: "آموزش پایتون رایگان مقدماتی تا پیشرفته + پروژه های جذاب",
        info: "حیف نیست محبوب ترین زبان برنامه نویسی دنیا رو  ناقص و بی هدف یادبگیری؟ آموزش پایتون از زیر صفر و پایه…",
        teacher: "رضا دولتی",
        score: 5,
        students: 93726,
        price: 6000000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: false,
        isSecurity: false,
        isPython: true,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/js.webp',
        title: "آموزش جاوا اسکریپت رایگان مقدماتی تا پیشرفته + مینی پروژه",
        info: "آموزش جاوا اسکریپت برای تمامی افرادی ک قصد ورود به زبان برنامه نویسی دارند مناسب می باشد . خصوصا برای…",
        teacher: "محمدامین سعیدی راد",
        score: 5,
        students: 71003,
        price: 4000000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/html.webp',
        title: "آموزش HTML رایگان مقدماتی تا پیشرفته",
        info: "آموزش HTML، اولین قدم شروع طراحی وبسایت است. HTML یه زبان نشانه گذاری هست که با کمک اون میتونی تگ…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 61886,
        price: 220000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/css.webp',
        title: "آموزش Css رایگان مقدماتی تا پیشرفته",
        info: "حالا وقتشه که با دوره آموزش CSS به اسکلتی که با html ساختی پوست و گوشت بدی تا تبدیل به…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 54027,
        price: 150000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/html-css.webp',
        title: "پروژه های خلاقانه با Html و Css(آپدیت  ۲۰۲۳)",
        info: "دوره  پروژه خلاقانه با HTML, CSS  با هدف تقویت CSS شما, با آموزش پروژه‌های پیشرفته و سطح بالا , طراحی…",
        teacher: "مهرشاد براتی",
        score: 5,
        students: 35839,
        price: 220000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/css-grid.webp',
        title: "آموزش پروژه محور CSS Grid + پروژه لندینگ رستوران",
        info: "Css grid یک ماژول مربوط به css است . کارکردن با این ماژول بسیار جذاب است و با امکانات و…",
        teacher: "مهرشاد براتی",
        score: 5,
        students: 32365,
        price: 35000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/flexbox.webp',
        title: "آموزش FlexBox پروژه محور + پروژه سایت هاستینگ",
        info: "اگر شما به حوزه طراحی و برنامه نویسی وب علاقه داشته باشید قطعا در مورد صفحه آرایی، ریسپانسیو سازی، فلکس…",
        teacher: "حمیدرضا عبادی",
        score: 5,
        students: 31895,
        price: 196000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: true,
        isSecurity: false,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    },
    {
        imgSrc: './Pictures/black-js.webp',
        title: "آموزش جاوااسکریپت با گرایش امنیت | جاوااسکریپت سیاه",
        info: "جاوااسکریپت همواره در لیست محبوب ترین زبان های برنامه نویسی برای هکرها و امنیت کارهاست ! و من در این دوره…",
        teacher: "قدیر یلمه",
        score: 5,
        students: 31114,
        price: 150000,
        offPercent: 100,
        isLastCourses: false,
        isPopularCourses: false,
        isLatestCourses: false,
        isMostPopularCourses: true,
        isFrontEnd: false,
        isSecurity: true,
        isPython: false,
        isPHP: false,
        isSkillUp: false,
        isSoftSkill: false
    }
]

const blogs = [{
        imgSrc: './Pictures/flowchart.jpg',
        title: "فلوچارت برنامه نویسی چیست؟",
        info: "در این مقاله از سبزلرن، به معرفی و اهمیت فلوچارت برنامه ‌نویسی پرداخته و روش‌ها و فواید آن را برای برنامه‌نویسان مورد بررسی قرار خواهیم داد. همچنین، به روش‌های استفاده…",
        author: "ارمیا مزرعه",
        dateDay: 19,
        dateMonth: 7,
        dateYear: 1403
    },
    {
        imgSrc: './Pictures/why-cant-learn-prog.webp',
        title: "چرا برنامه نویسی یاد نمی گیرم؟ 5 مانع یادگیری برنامه نویسی",
        info: "آیا تا به حال برای یادگیری برنامه‌نویسی تلاش کرده‌اید ولی به نظر رسیده که هیچ‌وقت به جایی نمی‌رسید؟ انگار هر چقدر هم تلاش می‌کنید، باز هم کدها مثل یک زبان…",
        author: "مهدی ایلخانی نسب",
        dateDay: 18,
        dateMonth: 7,
        dateYear: 1403
    },
    {
        imgSrc: './Pictures/cod.webp',
        title: "زبان برنامه نویسی بازی کال اف دیوتی موبایل",
        info: "بازی «کال آو دیوتی موبایل» یکی از آن بازی‌هایی است که خیلی‌ها را پای موبایلشان میخکوب کرده است. گرافیک فوق‌العاده، گیم‌پلی هیجان‌انگیز و تجربه‌ای که حس یک بازی کنسولی واقعی…",
        author: "مهدی ایلخانی نسب",
        dateDay: 17,
        dateMonth: 7,
        dateYear: 1403
    },
    {
        imgSrc: './Pictures/full-stack-roadmap-blog.webp',
        title: "نقشه راه برنامه نویس فول استک وب",
        info: "اگر به برنامه‌نویسی علاقه دارید و یا حتی چند وقتی است که مشغول یادگیری هستید، احتمالاً اصطلاح “برنامه‌نویس فول استک” به گوشتان خورده است. اما چه چیزی باعث شده که…",
        author: "مهدی ایلخانی نسب",
        dateDay: 16,
        dateMonth: 7,
        dateYear: 1403
    }
]

export {
    courses,
    blogs
}